name: Create Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # This is required for requesting the JWT

jobs:
  rl-scanner:
    uses: ./.github/workflows/rl-scanner.yml
    with:
      ruby-version: 3.2
    secrets:
      RLSECURE_LICENSE: ${{ secrets.RLSECURE_LICENSE }}
      RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
      SIGNAL_HANDLER_TOKEN: ${{ secrets.SIGNAL_HANDLER_TOKEN }}
      PRODSEC_TOOLS_USER: ${{ secrets.PRODSEC_TOOLS_USER }}
      PRODSEC_TOOLS_TOKEN: ${{ secrets.PRODSEC_TOOLS_TOKEN }}
      PRODSEC_TOOLS_ARN: ${{ secrets.PRODSEC_TOOLS_ARN }}

  release:
    uses: ./.github/workflows/ruby-release.yml
    needs: rl-scanner
    with:
      ruby-version: 3.2
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      rubygems-token: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
